#!/usr/bin/env python3
# @generated by scripts/generate-py-tau-api.py; do not edit by hand.
"""tau Python kernel — persistent REPL with reverse RPC for orchestration.

Runs as a subprocess. Communicates with the Rust host via JSON-lines over
stdin (host→kernel) and stdout (kernel→host). Stderr is for kernel diagnostics.

Protocol:
  Host→Kernel: {"type": "exec", "cell_id": "...", "code": "..."}
  Host→Kernel: {"type": "rpc_result", "id": "...", "result": ..., "error": ...}
  Host→Kernel: {"type": "shutdown"}
  Kernel→Host: {"type": "rpc", "id": "...", "method": "...", "params": {...}}
  Kernel→Host: {"type": "result", "cell_id": "...", "output": ..., "error": ..., "stdout": ..., "stderr": ...}
"""

import ast
import contextlib
import io
import json
import os
import sys
import traceback


# Keep references to the real stdin/stdout before any redirects.
# exec_cell uses contextlib.redirect_stdout which replaces sys.stdout,
# but RPC must always go through the actual pipe to the host.
_real_stdin = sys.stdin
_real_stdout = sys.stdout


class ThreadResult:
    """Structured result from tau.thread(), tau.launch(), tau.poll(), and tau.wait(). Provides attribute access to outcome fields while remaining string-compatible via __str__ and __contains__."""

    def __init__(self, data):
        if isinstance(data, str):
            self.status = 'completed'
            self.output = data
            self.trace = data
            self.alias = None
            self.duration_ms = None
            self.turns = None
            self.branch = None
            self.diff_stat = None
            self.files_changed = 0
        else:
            self.status = data.get("status", 'completed')
            self.output = data.get("output", '')
            self.trace = data.get("trace", '')
            self.alias = data.get("alias", None)
            self.duration_ms = data.get("duration_ms", None)
            self.turns = data.get("turns", None)
            self.branch = data.get("branch", None)
            self.diff_stat = data.get("diff_stat", None)
            self.files_changed = data.get("files_changed", 0)

    @property
    def completed(self):
        return self.status == "completed"

    @property
    def aborted(self):
        return self.status == "aborted"

    @property
    def escalated(self):
        return self.status == "escalated"

    @property
    def timed_out(self):
        return self.status == "timed_out"

    @property
    def running(self):
        return self.status == "running"

    @property
    def reason(self):
        return self.output

    def __str__(self):
        return self.trace

    def __repr__(self):
        return f"ThreadResult(status={self.status!r}, output={self.output[:60]!r})"

    def __bool__(self):
        return self.completed

    def __contains__(self, item):
        return item in self.trace


class DiffResult:
    """Result from tau.diff(). Contains diff info for a thread's worktree branch."""

    def __init__(self, data):
        self.branch = data.get("branch", '')
        self.stat = data.get("stat", '')
        self.diff = data.get("diff", '')
        self.files_changed = data.get("files_changed", 0)
        self.insertions = data.get("insertions", 0)
        self.deletions = data.get("deletions", 0)

    def __str__(self):
        return self.stat

    def __repr__(self):
        return f"DiffResult(branch={self.branch!r}, files_changed={self.files_changed})"

    def __bool__(self):
        return self.files_changed > 0


class MergeResult:
    """Result from tau.merge(). Indicates success or conflict."""

    def __init__(self, data):
        self.success = data.get("success", False)
        self.conflicts = data.get("conflicts", [])
        self.message = data.get("message", '')
        self.branch = data.get("branch", '')

    def __str__(self):
        return f"Merged {self.branch}" if self.success else f"Conflicts in: {', '.join(self.conflicts)}"

    def __repr__(self):
        return f"MergeResult(success={self.success!r}, conflicts={self.conflicts!r})"

    def __bool__(self):
        return self.success


class TauProxy:
    """The `tau` object available in the kernel namespace.

    All methods are blocking — they issue an RPC to the Rust host and wait
    for the response. No asyncio needed.
    """

    def __init__(self):
        self.cwd = os.getcwd()
        self.home_dir = os.path.expanduser("~")
        self.tmp_dir = os.environ.get("TMPDIR", "/tmp")
        self._rpc_counter = 0

    def _rpc(self, method, params):
        """Send an RPC request to the host and block until the response."""
        self._rpc_counter += 1
        rpc_id = f"rpc-{self._rpc_counter}"
        msg = {"type": "rpc", "id": rpc_id, "method": method, "params": params}
        _real_stdout.write(json.dumps(msg, default=str) + "\n")
        _real_stdout.flush()
        # Block reading stdin until we get the matching rpc_result
        while True:
            line = _real_stdin.readline()
            if not line:
                raise RuntimeError("Host closed connection")
            resp = json.loads(line)
            if resp.get("type") == "rpc_result" and resp.get("id") == rpc_id:
                if resp.get("error"):
                    raise RuntimeError(resp["error"])
                return resp.get("result")

    def _thread_params(
        self,
        alias,
        task,
        tools,
        model,
        episodes,
        timeout,
        max_turns,
        worktree,
        worktree_base,
        worktree_include,
    ):
        params = {"alias": alias, "task": task}
        if tools is not None:
            params["tools"] = tools
        if model is not None:
            params["model"] = model
        if episodes is not None:
            params["episodes"] = episodes
        if timeout is not None:
            params["timeout"] = timeout
        if max_turns is not None:
            params["max_turns"] = max_turns
        if worktree is not None:
            params["worktree"] = worktree
        if worktree_base is not None:
            params["worktree_base"] = worktree_base
        if worktree_include is not None:
            params["worktree_include"] = worktree_include
        return params

    def _coerce_alias(self, alias_or_result):
        if isinstance(alias_or_result, ThreadResult):
            return alias_or_result.alias
        if isinstance(alias_or_result, dict):
            return alias_or_result.get("alias")
        return alias_or_result

    def tool(self, name, **kwargs):
        """Call a tau tool by name. Returns the tool result text."""
        return self._rpc("tool", {"name": name, "args": kwargs})

    def thread(self, alias, task, tools=None, model=None, episodes=None, timeout=None, max_turns=None, worktree=None, worktree_base=None, worktree_include=None):
        """Spawn a thread. Blocks until complete. Returns a ThreadResult."""
        params = self._thread_params(
            alias,
            task,
            tools,
            model,
            episodes,
            timeout,
            max_turns,
            worktree,
            worktree_base,
            worktree_include,
        )
        return ThreadResult(self._rpc("thread", params))

    def launch(self, alias, task, tools=None, model=None, episodes=None, timeout=None, max_turns=None, worktree=None, worktree_base=None, worktree_include=None):
        """Launch a thread without blocking. Returns a ThreadResult with status='running'."""
        params = self._thread_params(
            alias,
            task,
            tools,
            model,
            episodes,
            timeout,
            max_turns,
            worktree,
            worktree_base,
            worktree_include,
        )
        return ThreadResult(self._rpc("launch", params))

    def poll(self, alias):
        """Inspect the current status of a launched thread."""
        return ThreadResult(self._rpc("poll", {"alias": self._coerce_alias(alias)}))

    def wait(self, aliases, timeout=None):
        """Wait for launched threads to finish, returning partial results on timeout."""
        normalized = [self._coerce_alias(alias) for alias in aliases]
        params = {"aliases": normalized}
        if timeout is not None:
            params["timeout"] = timeout
        return [ThreadResult(item) for item in self._rpc("wait", params)]

    def query(self, prompt, alias=None, model=None):
        """Single-shot LLM query. Returns response text."""
        params = {"prompt": prompt}
        if alias is not None:
            params["alias"] = alias
        if model is not None:
            params["model"] = model
        return self._rpc("query", params)

    def parallel(self, *specs):
        """Execute multiple operations concurrently. Specs should be created with tau.Thread(), tau.Query(), or tau.Tool()."""
        raw = self._rpc("parallel", {"specs": list(specs)})
        specs_list = list(specs)
        wrapped = []
        for i, val in enumerate(raw):
            if i < len(specs_list) and specs_list[i].get("method") == "thread":
                wrapped.append(ThreadResult(val))
            else:
                wrapped.append(val)
        return wrapped

    def document(self, operation, name=None, content=None):
        """Access shared virtual documents. Operations: read, write, append, list."""
        params = {"operation": operation}
        if name is not None:
            params["name"] = name
        if content is not None:
            params["content"] = content
        return self._rpc("document", params)

    def log(self, message):
        """Record a message in the orchestration trace."""
        self._rpc("log", {"message": str(message)})

    def diff(self, alias):
        """Get diff for a thread's worktree branch. Returns a DiffResult."""
        return DiffResult(self._rpc("diff", {"alias": alias}))

    def merge(self, alias):
        """Merge a thread's worktree branch into the current branch. Returns a MergeResult."""
        return MergeResult(self._rpc("merge", {"alias": alias}))

    def branches(self):
        """List active tau thread branches."""
        return self._rpc("branches", {})

    # --- Spec factories for tau.parallel() ---

    @staticmethod
    def Thread(alias, task, **kwargs):
        """Create a thread spec for use with tau.parallel()."""
        return {"method": "thread", "alias": alias, "task": task, **kwargs}

    @staticmethod
    def Query(prompt, **kwargs):
        """Create a query spec for use with tau.parallel()."""
        return {"method": "query", "prompt": prompt, **kwargs}

    @staticmethod
    def Tool(name, **kwargs):
        """Create a tool spec for use with tau.parallel()."""
        return {"method": "tool", "name": name, "args": kwargs}


def exec_cell(code, namespace):
    """Execute a code cell in the given namespace.

    Returns (output, error, stdout, stderr).
    If the last statement is an expression, its repr is returned as output.
    """
    stdout_buf = io.StringIO()
    stderr_buf = io.StringIO()
    output = None
    error = None

    try:
        tree = ast.parse(code)
        last_expr = None
        # If the last statement is a bare expression, extract it
        # so we can eval it and return its value (REPL-style).
        if tree.body and isinstance(tree.body[-1], ast.Expr):
            last_expr = tree.body.pop()

        with contextlib.redirect_stdout(stdout_buf), contextlib.redirect_stderr(stderr_buf):
            if tree.body:
                compiled = compile(tree, "<cell>", "exec")
                exec(compiled, namespace)
            if last_expr:
                expr_code = compile(
                    ast.Expression(body=last_expr.value), "<cell>", "eval"
                )
                result = eval(expr_code, namespace)
                if result is not None:
                    output = repr(result)
    except Exception:
        error = traceback.format_exc()

    return output, error, stdout_buf.getvalue(), stderr_buf.getvalue()


def main():
    namespace = {
        "tau": TauProxy(),
        "ThreadResult": ThreadResult,
        "DiffResult": DiffResult,
        "MergeResult": MergeResult,
        "__name__": "__main__",
    }

    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            msg = json.loads(line)
        except json.JSONDecodeError:
            continue

        msg_type = msg.get("type")

        if msg_type == "shutdown":
            break

        if msg_type == "exec":
            cell_id = msg["cell_id"]
            code = msg["code"]
            output, error, stdout, stderr = exec_cell(code, namespace)
            result = {
                "type": "result",
                "cell_id": cell_id,
                "output": output,
                "error": error,
                "stdout": stdout,
                "stderr": stderr,
            }
            sys.stdout.write(json.dumps(result) + "\n")
            sys.stdout.flush()


if __name__ == "__main__":
    main()
