//! Built-in model catalog — ported from models.generated.ts
//!
//! Providers included: anthropic, openai, kimi-coding.

use crate::types::{known_api, Model, ModelCost};

/// Config struct grouping provider identity fields for [`m`].
struct Prov {
    api: &'static str,
    provider: &'static str,
    base_url: &'static str,
}

/// Config struct grouping cost and window limits for [`m`].
struct Limits {
    cost_in: f64,
    cost_out: f64,
    cost_cr: f64,
    cost_cw: f64,
    ctx: u64,
    max_tok: u64,
}

fn m(id: &str, name: &str, prov: Prov, reasoning: bool, input: &[&str], lim: Limits) -> Model {
    Model {
        id: id.into(),
        name: name.into(),
        api: prov.api.into(),
        provider: prov.provider.into(),
        base_url: prov.base_url.into(),
        reasoning,
        input: input.iter().map(|s| s.to_string()).collect(),
        cost: ModelCost {
            input: lim.cost_in,
            output: lim.cost_out,
            cache_read: lim.cost_cr,
            cache_write: lim.cost_cw,
        },
        context_window: lim.ctx,
        max_tokens: lim.max_tok,
        headers: None,
        compat: None,
    }
}

const ANTHROPIC_URL: &str = "https://api.anthropic.com";
const OPENAI_URL: &str = "https://api.openai.com/v1";
const KIMI_URL: &str = "https://api.kimi.com/coding";
const AM: &str = known_api::ANTHROPIC_MESSAGES;
const OR: &str = known_api::OPENAI_RESPONSES;
const TI: &[&str] = &["text", "image"];
const T: &[&str] = &["text"];

const AN: Prov = Prov {
    api: AM,
    provider: "anthropic",
    base_url: ANTHROPIC_URL,
};
const OA: Prov = Prov {
    api: OR,
    provider: "openai",
    base_url: OPENAI_URL,
};
const KI: Prov = Prov {
    api: AM,
    provider: "kimi-coding",
    base_url: KIMI_URL,
};

pub fn builtin_models() -> Vec<Model> {
    vec![
        // -----------------------------------------------------------------------
        // anthropic
        // -----------------------------------------------------------------------
        m(
            "claude-3-5-haiku-20241022",
            "Claude Haiku 3.5",
            AN,
            false,
            TI,
            Limits {
                cost_in: 0.8,
                cost_out: 4.0,
                cost_cr: 0.08,
                cost_cw: 1.0,
                ctx: 200_000,
                max_tok: 8_192,
            },
        ),
        m(
            "claude-3-5-haiku-latest",
            "Claude Haiku 3.5 (latest)",
            AN,
            false,
            TI,
            Limits {
                cost_in: 0.8,
                cost_out: 4.0,
                cost_cr: 0.08,
                cost_cw: 1.0,
                ctx: 200_000,
                max_tok: 8_192,
            },
        ),
        m(
            "claude-3-5-sonnet-20240620",
            "Claude Sonnet 3.5",
            AN,
            false,
            TI,
            Limits {
                cost_in: 3.0,
                cost_out: 15.0,
                cost_cr: 0.3,
                cost_cw: 3.75,
                ctx: 200_000,
                max_tok: 8_192,
            },
        ),
        m(
            "claude-3-5-sonnet-20241022",
            "Claude Sonnet 3.5 v2",
            AN,
            false,
            TI,
            Limits {
                cost_in: 3.0,
                cost_out: 15.0,
                cost_cr: 0.3,
                cost_cw: 3.75,
                ctx: 200_000,
                max_tok: 8_192,
            },
        ),
        m(
            "claude-3-7-sonnet-20250219",
            "Claude Sonnet 3.7",
            AN,
            true,
            TI,
            Limits {
                cost_in: 3.0,
                cost_out: 15.0,
                cost_cr: 0.3,
                cost_cw: 3.75,
                ctx: 200_000,
                max_tok: 64_000,
            },
        ),
        m(
            "claude-3-7-sonnet-latest",
            "Claude Sonnet 3.7 (latest)",
            AN,
            true,
            TI,
            Limits {
                cost_in: 3.0,
                cost_out: 15.0,
                cost_cr: 0.3,
                cost_cw: 3.75,
                ctx: 200_000,
                max_tok: 64_000,
            },
        ),
        m(
            "claude-3-haiku-20240307",
            "Claude Haiku 3",
            AN,
            false,
            TI,
            Limits {
                cost_in: 0.25,
                cost_out: 1.25,
                cost_cr: 0.03,
                cost_cw: 0.3,
                ctx: 200_000,
                max_tok: 4_096,
            },
        ),
        m(
            "claude-3-opus-20240229",
            "Claude Opus 3",
            AN,
            false,
            TI,
            Limits {
                cost_in: 15.0,
                cost_out: 75.0,
                cost_cr: 1.5,
                cost_cw: 18.75,
                ctx: 200_000,
                max_tok: 4_096,
            },
        ),
        m(
            "claude-3-sonnet-20240229",
            "Claude Sonnet 3",
            AN,
            false,
            TI,
            Limits {
                cost_in: 3.0,
                cost_out: 15.0,
                cost_cr: 0.3,
                cost_cw: 0.3,
                ctx: 200_000,
                max_tok: 4_096,
            },
        ),
        m(
            "claude-haiku-4-5",
            "Claude Haiku 4.5 (latest)",
            AN,
            true,
            TI,
            Limits {
                cost_in: 1.0,
                cost_out: 5.0,
                cost_cr: 0.1,
                cost_cw: 1.25,
                ctx: 200_000,
                max_tok: 64_000,
            },
        ),
        m(
            "claude-haiku-4-5-20251001",
            "Claude Haiku 4.5",
            AN,
            true,
            TI,
            Limits {
                cost_in: 1.0,
                cost_out: 5.0,
                cost_cr: 0.1,
                cost_cw: 1.25,
                ctx: 200_000,
                max_tok: 64_000,
            },
        ),
        m(
            "claude-opus-4-0",
            "Claude Opus 4 (latest)",
            AN,
            true,
            TI,
            Limits {
                cost_in: 15.0,
                cost_out: 75.0,
                cost_cr: 1.5,
                cost_cw: 18.75,
                ctx: 200_000,
                max_tok: 32_000,
            },
        ),
        m(
            "claude-opus-4-1",
            "Claude Opus 4.1 (latest)",
            AN,
            true,
            TI,
            Limits {
                cost_in: 15.0,
                cost_out: 75.0,
                cost_cr: 1.5,
                cost_cw: 18.75,
                ctx: 200_000,
                max_tok: 32_000,
            },
        ),
        m(
            "claude-opus-4-1-20250805",
            "Claude Opus 4.1",
            AN,
            true,
            TI,
            Limits {
                cost_in: 15.0,
                cost_out: 75.0,
                cost_cr: 1.5,
                cost_cw: 18.75,
                ctx: 200_000,
                max_tok: 32_000,
            },
        ),
        m(
            "claude-opus-4-20250514",
            "Claude Opus 4",
            AN,
            true,
            TI,
            Limits {
                cost_in: 15.0,
                cost_out: 75.0,
                cost_cr: 1.5,
                cost_cw: 18.75,
                ctx: 200_000,
                max_tok: 32_000,
            },
        ),
        m(
            "claude-opus-4-5",
            "Claude Opus 4.5 (latest)",
            AN,
            true,
            TI,
            Limits {
                cost_in: 5.0,
                cost_out: 25.0,
                cost_cr: 0.5,
                cost_cw: 6.25,
                ctx: 200_000,
                max_tok: 64_000,
            },
        ),
        m(
            "claude-opus-4-5-20251101",
            "Claude Opus 4.5",
            AN,
            true,
            TI,
            Limits {
                cost_in: 5.0,
                cost_out: 25.0,
                cost_cr: 0.5,
                cost_cw: 6.25,
                ctx: 200_000,
                max_tok: 64_000,
            },
        ),
        m(
            "claude-opus-4-6",
            "Claude Opus 4.6",
            AN,
            true,
            TI,
            Limits {
                cost_in: 5.0,
                cost_out: 25.0,
                cost_cr: 0.5,
                cost_cw: 6.25,
                ctx: 200_000,
                max_tok: 128_000,
            },
        ),
        m(
            "claude-sonnet-4-0",
            "Claude Sonnet 4 (latest)",
            AN,
            true,
            TI,
            Limits {
                cost_in: 3.0,
                cost_out: 15.0,
                cost_cr: 0.3,
                cost_cw: 3.75,
                ctx: 200_000,
                max_tok: 64_000,
            },
        ),
        m(
            "claude-sonnet-4-20250514",
            "Claude Sonnet 4",
            AN,
            true,
            TI,
            Limits {
                cost_in: 3.0,
                cost_out: 15.0,
                cost_cr: 0.3,
                cost_cw: 3.75,
                ctx: 200_000,
                max_tok: 64_000,
            },
        ),
        m(
            "claude-sonnet-4-5",
            "Claude Sonnet 4.5 (latest)",
            AN,
            true,
            TI,
            Limits {
                cost_in: 3.0,
                cost_out: 15.0,
                cost_cr: 0.3,
                cost_cw: 3.75,
                ctx: 200_000,
                max_tok: 64_000,
            },
        ),
        m(
            "claude-sonnet-4-5-20250929",
            "Claude Sonnet 4.5",
            AN,
            true,
            TI,
            Limits {
                cost_in: 3.0,
                cost_out: 15.0,
                cost_cr: 0.3,
                cost_cw: 3.75,
                ctx: 200_000,
                max_tok: 64_000,
            },
        ),
        m(
            "claude-sonnet-4-6",
            "Claude Sonnet 4.6",
            AN,
            true,
            TI,
            Limits {
                cost_in: 3.0,
                cost_out: 15.0,
                cost_cr: 0.3,
                cost_cw: 3.75,
                ctx: 200_000,
                max_tok: 64_000,
            },
        ),
        // -----------------------------------------------------------------------
        // openai
        // -----------------------------------------------------------------------
        m(
            "codex-mini-latest",
            "Codex Mini",
            OA,
            true,
            T,
            Limits {
                cost_in: 1.5,
                cost_out: 6.0,
                cost_cr: 0.375,
                cost_cw: 0.0,
                ctx: 200_000,
                max_tok: 100_000,
            },
        ),
        m(
            "gpt-4",
            "GPT-4",
            OA,
            false,
            T,
            Limits {
                cost_in: 30.0,
                cost_out: 60.0,
                cost_cr: 0.0,
                cost_cw: 0.0,
                ctx: 8_192,
                max_tok: 8_192,
            },
        ),
        m(
            "gpt-4-turbo",
            "GPT-4 Turbo",
            OA,
            false,
            TI,
            Limits {
                cost_in: 10.0,
                cost_out: 30.0,
                cost_cr: 0.0,
                cost_cw: 0.0,
                ctx: 128_000,
                max_tok: 4_096,
            },
        ),
        m(
            "gpt-4.1",
            "GPT-4.1",
            OA,
            false,
            TI,
            Limits {
                cost_in: 2.0,
                cost_out: 8.0,
                cost_cr: 0.5,
                cost_cw: 0.0,
                ctx: 1_047_576,
                max_tok: 32_768,
            },
        ),
        m(
            "gpt-4.1-mini",
            "GPT-4.1 mini",
            OA,
            false,
            TI,
            Limits {
                cost_in: 0.4,
                cost_out: 1.6,
                cost_cr: 0.1,
                cost_cw: 0.0,
                ctx: 1_047_576,
                max_tok: 32_768,
            },
        ),
        m(
            "gpt-4.1-nano",
            "GPT-4.1 nano",
            OA,
            false,
            TI,
            Limits {
                cost_in: 0.1,
                cost_out: 0.4,
                cost_cr: 0.03,
                cost_cw: 0.0,
                ctx: 1_047_576,
                max_tok: 32_768,
            },
        ),
        m(
            "gpt-4o",
            "GPT-4o",
            OA,
            false,
            TI,
            Limits {
                cost_in: 2.5,
                cost_out: 10.0,
                cost_cr: 1.25,
                cost_cw: 0.0,
                ctx: 128_000,
                max_tok: 16_384,
            },
        ),
        m(
            "gpt-4o-2024-05-13",
            "GPT-4o (2024-05-13)",
            OA,
            false,
            TI,
            Limits {
                cost_in: 5.0,
                cost_out: 15.0,
                cost_cr: 0.0,
                cost_cw: 0.0,
                ctx: 128_000,
                max_tok: 4_096,
            },
        ),
        m(
            "gpt-4o-2024-08-06",
            "GPT-4o (2024-08-06)",
            OA,
            false,
            TI,
            Limits {
                cost_in: 2.5,
                cost_out: 10.0,
                cost_cr: 1.25,
                cost_cw: 0.0,
                ctx: 128_000,
                max_tok: 16_384,
            },
        ),
        m(
            "gpt-4o-2024-11-20",
            "GPT-4o (2024-11-20)",
            OA,
            false,
            TI,
            Limits {
                cost_in: 2.5,
                cost_out: 10.0,
                cost_cr: 1.25,
                cost_cw: 0.0,
                ctx: 128_000,
                max_tok: 16_384,
            },
        ),
        m(
            "gpt-4o-mini",
            "GPT-4o mini",
            OA,
            false,
            TI,
            Limits {
                cost_in: 0.15,
                cost_out: 0.6,
                cost_cr: 0.08,
                cost_cw: 0.0,
                ctx: 128_000,
                max_tok: 16_384,
            },
        ),
        m(
            "gpt-5",
            "GPT-5",
            OA,
            true,
            TI,
            Limits {
                cost_in: 1.25,
                cost_out: 10.0,
                cost_cr: 0.125,
                cost_cw: 0.0,
                ctx: 400_000,
                max_tok: 128_000,
            },
        ),
        m(
            "gpt-5-chat-latest",
            "GPT-5 Chat Latest",
            OA,
            false,
            TI,
            Limits {
                cost_in: 1.25,
                cost_out: 10.0,
                cost_cr: 0.125,
                cost_cw: 0.0,
                ctx: 128_000,
                max_tok: 16_384,
            },
        ),
        m(
            "gpt-5-codex",
            "GPT-5-Codex",
            OA,
            true,
            TI,
            Limits {
                cost_in: 1.25,
                cost_out: 10.0,
                cost_cr: 0.125,
                cost_cw: 0.0,
                ctx: 400_000,
                max_tok: 128_000,
            },
        ),
        m(
            "gpt-5-mini",
            "GPT-5 Mini",
            OA,
            true,
            TI,
            Limits {
                cost_in: 0.25,
                cost_out: 2.0,
                cost_cr: 0.025,
                cost_cw: 0.0,
                ctx: 400_000,
                max_tok: 128_000,
            },
        ),
        m(
            "gpt-5-nano",
            "GPT-5 Nano",
            OA,
            true,
            TI,
            Limits {
                cost_in: 0.05,
                cost_out: 0.4,
                cost_cr: 0.005,
                cost_cw: 0.0,
                ctx: 400_000,
                max_tok: 128_000,
            },
        ),
        m(
            "gpt-5-pro",
            "GPT-5 Pro",
            OA,
            true,
            TI,
            Limits {
                cost_in: 15.0,
                cost_out: 120.0,
                cost_cr: 0.0,
                cost_cw: 0.0,
                ctx: 400_000,
                max_tok: 272_000,
            },
        ),
        m(
            "gpt-5.1",
            "GPT-5.1",
            OA,
            true,
            TI,
            Limits {
                cost_in: 1.25,
                cost_out: 10.0,
                cost_cr: 0.13,
                cost_cw: 0.0,
                ctx: 400_000,
                max_tok: 128_000,
            },
        ),
        m(
            "gpt-5.1-chat-latest",
            "GPT-5.1 Chat",
            OA,
            true,
            TI,
            Limits {
                cost_in: 1.25,
                cost_out: 10.0,
                cost_cr: 0.125,
                cost_cw: 0.0,
                ctx: 128_000,
                max_tok: 16_384,
            },
        ),
        m(
            "gpt-5.1-codex",
            "GPT-5.1 Codex",
            OA,
            true,
            TI,
            Limits {
                cost_in: 1.25,
                cost_out: 10.0,
                cost_cr: 0.125,
                cost_cw: 0.0,
                ctx: 400_000,
                max_tok: 128_000,
            },
        ),
        m(
            "gpt-5.1-codex-max",
            "GPT-5.1 Codex Max",
            OA,
            true,
            TI,
            Limits {
                cost_in: 1.25,
                cost_out: 10.0,
                cost_cr: 0.125,
                cost_cw: 0.0,
                ctx: 400_000,
                max_tok: 128_000,
            },
        ),
        m(
            "gpt-5.1-codex-mini",
            "GPT-5.1 Codex mini",
            OA,
            true,
            TI,
            Limits {
                cost_in: 0.25,
                cost_out: 2.0,
                cost_cr: 0.025,
                cost_cw: 0.0,
                ctx: 400_000,
                max_tok: 128_000,
            },
        ),
        m(
            "gpt-5.2",
            "GPT-5.2",
            OA,
            true,
            TI,
            Limits {
                cost_in: 1.75,
                cost_out: 14.0,
                cost_cr: 0.175,
                cost_cw: 0.0,
                ctx: 400_000,
                max_tok: 128_000,
            },
        ),
        m(
            "gpt-5.2-chat-latest",
            "GPT-5.2 Chat",
            OA,
            true,
            TI,
            Limits {
                cost_in: 1.75,
                cost_out: 14.0,
                cost_cr: 0.175,
                cost_cw: 0.0,
                ctx: 128_000,
                max_tok: 16_384,
            },
        ),
        m(
            "gpt-5.2-codex",
            "GPT-5.2 Codex",
            OA,
            true,
            TI,
            Limits {
                cost_in: 1.75,
                cost_out: 14.0,
                cost_cr: 0.175,
                cost_cw: 0.0,
                ctx: 400_000,
                max_tok: 128_000,
            },
        ),
        m(
            "gpt-5.2-pro",
            "GPT-5.2 Pro",
            OA,
            true,
            TI,
            Limits {
                cost_in: 21.0,
                cost_out: 168.0,
                cost_cr: 0.0,
                cost_cw: 0.0,
                ctx: 400_000,
                max_tok: 128_000,
            },
        ),
        m(
            "gpt-5.3-codex",
            "GPT-5.3 Codex",
            OA,
            true,
            TI,
            Limits {
                cost_in: 1.75,
                cost_out: 14.0,
                cost_cr: 0.175,
                cost_cw: 0.0,
                ctx: 400_000,
                max_tok: 128_000,
            },
        ),
        m(
            "gpt-5.3-codex-spark",
            "GPT-5.3 Codex Spark",
            OA,
            true,
            TI,
            Limits {
                cost_in: 1.75,
                cost_out: 14.0,
                cost_cr: 0.175,
                cost_cw: 0.0,
                ctx: 128_000,
                max_tok: 32_000,
            },
        ),
        m(
            "gpt-5.4",
            "GPT-5.4",
            OA,
            true,
            TI,
            Limits {
                cost_in: 2.5,
                cost_out: 15.0,
                cost_cr: 0.25,
                cost_cw: 0.0,
                ctx: 1_050_000,
                max_tok: 128_000,
            },
        ),
        m(
            "gpt-5.4-mini",
            "GPT-5.4 mini",
            OA,
            true,
            TI,
            Limits {
                cost_in: 0.75,
                cost_out: 4.5,
                cost_cr: 0.08,
                cost_cw: 0.0,
                ctx: 400_000,
                max_tok: 128_000,
            },
        ),
        m(
            "gpt-5.4-nano",
            "GPT-5.4 nano",
            OA,
            true,
            TI,
            Limits {
                cost_in: 0.2,
                cost_out: 1.25,
                cost_cr: 0.02,
                cost_cw: 0.0,
                ctx: 400_000,
                max_tok: 128_000,
            },
        ),
        m(
            "o1",
            "o1",
            OA,
            true,
            TI,
            Limits {
                cost_in: 15.0,
                cost_out: 60.0,
                cost_cr: 7.5,
                cost_cw: 0.0,
                ctx: 200_000,
                max_tok: 100_000,
            },
        ),
        m(
            "o1-pro",
            "o1-pro",
            OA,
            true,
            TI,
            Limits {
                cost_in: 150.0,
                cost_out: 600.0,
                cost_cr: 0.0,
                cost_cw: 0.0,
                ctx: 200_000,
                max_tok: 100_000,
            },
        ),
        m(
            "o3",
            "o3",
            OA,
            true,
            TI,
            Limits {
                cost_in: 2.0,
                cost_out: 8.0,
                cost_cr: 0.5,
                cost_cw: 0.0,
                ctx: 200_000,
                max_tok: 100_000,
            },
        ),
        m(
            "o3-deep-research",
            "o3-deep-research",
            OA,
            true,
            TI,
            Limits {
                cost_in: 10.0,
                cost_out: 40.0,
                cost_cr: 2.5,
                cost_cw: 0.0,
                ctx: 200_000,
                max_tok: 100_000,
            },
        ),
        m(
            "o3-mini",
            "o3-mini",
            OA,
            true,
            T,
            Limits {
                cost_in: 1.1,
                cost_out: 4.4,
                cost_cr: 0.55,
                cost_cw: 0.0,
                ctx: 200_000,
                max_tok: 100_000,
            },
        ),
        m(
            "o3-pro",
            "o3-pro",
            OA,
            true,
            TI,
            Limits {
                cost_in: 20.0,
                cost_out: 80.0,
                cost_cr: 0.0,
                cost_cw: 0.0,
                ctx: 200_000,
                max_tok: 100_000,
            },
        ),
        m(
            "o4-mini",
            "o4-mini",
            OA,
            true,
            TI,
            Limits {
                cost_in: 1.1,
                cost_out: 4.4,
                cost_cr: 0.28,
                cost_cw: 0.0,
                ctx: 200_000,
                max_tok: 100_000,
            },
        ),
        m(
            "o4-mini-deep-research",
            "o4-mini-deep-research",
            OA,
            true,
            TI,
            Limits {
                cost_in: 2.0,
                cost_out: 8.0,
                cost_cr: 0.5,
                cost_cw: 0.0,
                ctx: 200_000,
                max_tok: 100_000,
            },
        ),
        // -----------------------------------------------------------------------
        // kimi-coding
        // -----------------------------------------------------------------------
        m(
            "k2p5",
            "Kimi K2.5",
            KI,
            true,
            TI,
            Limits {
                cost_in: 0.0,
                cost_out: 0.0,
                cost_cr: 0.0,
                cost_cw: 0.0,
                ctx: 262_144,
                max_tok: 32_768,
            },
        ),
        m(
            "kimi-k2-thinking",
            "Kimi K2 Thinking",
            KI,
            true,
            T,
            Limits {
                cost_in: 0.0,
                cost_out: 0.0,
                cost_cr: 0.0,
                cost_cw: 0.0,
                ctx: 262_144,
                max_tok: 32_768,
            },
        ),
    ]
}
