#!/usr/bin/env python3
"""Generate Tau Python API artifacts from coding-agent/prompts/py_tau_api.json."""

from __future__ import annotations

import argparse
import difflib
import json
import pathlib
import sys
import textwrap
from typing import Any


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
MANIFEST_PATH = REPO_ROOT / "coding-agent" / "prompts" / "py_tau_api.json"
KERNEL_PATH = REPO_ROOT / "coding-agent" / "prompts" / "py_kernel.py"
GENERATED_DIR = REPO_ROOT / "coding-agent" / "prompts" / "generated"
REFERENCE_PATH = GENERATED_DIR / "py_tau_api_reference.md"
DESCRIPTION_PATH = GENERATED_DIR / "py_repl_description.txt"
GUIDELINE_PATH = GENERATED_DIR / "py_repl_guideline.txt"

HEADER_PY = "# @generated by scripts/generate-py-tau-api.py; do not edit by hand.\n"
HEADER_MD = "<!-- @generated by scripts/generate-py-tau-api.py; do not edit by hand. -->\n"


def py_literal(value: Any) -> str:
    return repr(value)


def load_manifest() -> dict[str, Any]:
    with MANIFEST_PATH.open() as f:
        return json.load(f)


def render_result_type(result: dict[str, Any]) -> str:
    lines: list[str] = [
        f"class {result['name']}:",
        f'    """{result["doc"]}"""',
        "",
        "    def __init__(self, data):",
    ]
    fallback = result.get("string_fallback")
    if fallback:
        lines.append("        if isinstance(data, str):")
        for name, value in fallback.items():
            expr = "data" if value == "$data" else py_literal(value)
            lines.append(f"            self.{name} = {expr}")
        lines.append("        else:")
        field_indent = " " * 12
    else:
        field_indent = " " * 8
    for field in result["fields"]:
        default = py_literal(field.get("default"))
        lines.append(f'{field_indent}self.{field["name"]} = data.get("{field["name"]}", {default})')

    for prop in result.get("properties", []):
        lines.extend(
            [
                "",
                "    @property",
                f"    def {prop['name']}(self):",
                f"        return {prop['expression']}",
            ]
        )

    lines.extend(
        [
            "",
            "    def __str__(self):",
            f"        return {result['str']}",
            "",
            "    def __repr__(self):",
            f"        return {result['repr']}",
            "",
            "    def __bool__(self):",
            f"        return {result['bool']}",
        ]
    )
    if "contains" in result:
        lines.extend(
            [
                "",
                "    def __contains__(self, item):",
                f"        return {result['contains']}",
            ]
        )
    return "\n".join(lines)


def render_thread_params(manifest: dict[str, Any]) -> str:
    params = [p["name"] for p in manifest["thread_params"]]
    signature = "\n".join(f"        {name}," for name in params)
    lines = [
        "    def _thread_params(",
        "        self,",
        signature,
        "    ):",
        '        params = {"alias": alias, "task": task}',
    ]
    for name in params[2:]:
        lines.extend(
            [
                f"        if {name} is not None:",
                f'            params["{name}"] = {name}',
            ]
        )
    lines.append("        return params")
    return "\n".join(lines)


def render_method(method: dict[str, Any]) -> str:
    lines = [f"    def {method['signature']}:", f'        """{method["summary"]}"""']
    kind = method["kind"]
    rpc = method["rpc"]
    if kind == "tool":
        lines.append(f'        return self._rpc("{rpc}", {{"name": name, "args": kwargs}})')
    elif kind == "thread":
        wrapper = method["wrapper"]
        names = ["alias", "task", "tools", "model", "episodes", "timeout", "max_turns", "worktree", "worktree_base", "worktree_include"]
        lines.append("        params = self._thread_params(")
        for name in names:
            lines.append(f"            {name},")
        lines.append("        )")
        lines.append(f'        return {wrapper}(self._rpc("{rpc}", params))')
    elif kind == "poll":
        wrapper = method["wrapper"]
        lines.append(f'        return {wrapper}(self._rpc("{rpc}", {{"alias": self._coerce_alias(alias)}}))')
    elif kind == "wait":
        lines.extend(
            [
                "        normalized = [self._coerce_alias(alias) for alias in aliases]",
                '        params = {"aliases": normalized}',
                "        if timeout is not None:",
                '            params["timeout"] = timeout',
                f'        return [ThreadResult(item) for item in self._rpc("{rpc}", params)]',
            ]
        )
    elif kind == "query":
        lines.extend(
            [
                '        params = {"prompt": prompt}',
                "        if alias is not None:",
                '            params["alias"] = alias',
                "        if model is not None:",
                '            params["model"] = model',
                f'        return self._rpc("{rpc}", params)',
            ]
        )
    elif kind == "parallel":
        lines.extend(
            [
                f'        raw = self._rpc("{rpc}", {{"specs": list(specs)}})',
                "        specs_list = list(specs)",
                "        wrapped = []",
                "        for i, val in enumerate(raw):",
                '            if i < len(specs_list) and specs_list[i].get("method") == "thread":',
                "                wrapped.append(ThreadResult(val))",
                "            else:",
                "                wrapped.append(val)",
                "        return wrapped",
            ]
        )
    elif kind == "document":
        lines.extend(
            [
                '        params = {"operation": operation}',
                "        if name is not None:",
                '            params["name"] = name',
                "        if content is not None:",
                '            params["content"] = content',
                f'        return self._rpc("{rpc}", params)',
            ]
        )
    elif kind == "log":
        lines.append(f'        self._rpc("{rpc}", {{"message": str(message)}})')
    elif kind == "alias_result":
        wrapper = method["wrapper"]
        lines.append(f'        return {wrapper}(self._rpc("{rpc}", {{"alias": alias}}))')
    elif kind == "no_params":
        lines.append(f'        return self._rpc("{rpc}", {{}})')
    else:
        raise ValueError(f"unknown method kind: {kind}")
    return "\n".join(lines)


def render_factory(factory: dict[str, Any]) -> str:
    lines = [
        "    @staticmethod",
        f"    def {factory['signature']}:",
        f'        """{factory["summary"]}"""',
    ]
    fields = ", ".join(f'"{field}": {field}' for field in factory["fields"])
    if factory.get("args_field"):
        lines.append(f'        return {{"method": "{factory["method"]}", {fields}, "{factory["args_field"]}": kwargs}}')
    else:
        lines.append(f'        return {{"method": "{factory["method"]}", {fields}, **kwargs}}')
    return "\n".join(lines)


def render_kernel(manifest: dict[str, Any]) -> str:
    result_types = "\n\n\n".join(render_result_type(result) for result in manifest["result_types"])
    thread_params = render_thread_params(manifest)
    methods = "\n\n".join(render_method(method) for method in manifest["methods"])
    factories = "\n\n".join(render_factory(factory) for factory in manifest["factories"])
    namespace_results = "\n".join(
        f'        "{result["name"]}": {result["name"]},' for result in manifest["result_types"]
    )
    return (
        '''#!/usr/bin/env python3
'''
        + HEADER_PY
        + '''"""tau Python kernel — persistent REPL with reverse RPC for orchestration.

Runs as a subprocess. Communicates with the Rust host via JSON-lines over
stdin (host→kernel) and stdout (kernel→host). Stderr is for kernel diagnostics.

Protocol:
  Host→Kernel: {"type": "exec", "cell_id": "...", "code": "..."}
  Host→Kernel: {"type": "rpc_result", "id": "...", "result": ..., "error": ...}
  Host→Kernel: {"type": "shutdown"}
  Kernel→Host: {"type": "rpc", "id": "...", "method": "...", "params": {...}}
  Kernel→Host: {"type": "result", "cell_id": "...", "output": ..., "error": ..., "stdout": ..., "stderr": ...}
"""

import ast
import contextlib
import io
import json
import os
import sys
import traceback


# Keep references to the real stdin/stdout before any redirects.
# exec_cell uses contextlib.redirect_stdout which replaces sys.stdout,
# but RPC must always go through the actual pipe to the host.
_real_stdin = sys.stdin
_real_stdout = sys.stdout


'''
        + result_types
        + '''


class TauProxy:
    """The `tau` object available in the kernel namespace.

    All methods are blocking — they issue an RPC to the Rust host and wait
    for the response. No asyncio needed.
    """

    def __init__(self):
        self.cwd = os.getcwd()
        self.home_dir = os.path.expanduser("~")
        self.tmp_dir = os.environ.get("TMPDIR", "/tmp")
        self._rpc_counter = 0

    def _rpc(self, method, params):
        """Send an RPC request to the host and block until the response."""
        self._rpc_counter += 1
        rpc_id = f"rpc-{self._rpc_counter}"
        msg = {"type": "rpc", "id": rpc_id, "method": method, "params": params}
        _real_stdout.write(json.dumps(msg, default=str) + "\\n")
        _real_stdout.flush()
        # Block reading stdin until we get the matching rpc_result
        while True:
            line = _real_stdin.readline()
            if not line:
                raise RuntimeError("Host closed connection")
            resp = json.loads(line)
            if resp.get("type") == "rpc_result" and resp.get("id") == rpc_id:
                if resp.get("error"):
                    raise RuntimeError(resp["error"])
                return resp.get("result")

'''
        + thread_params
        + '''

    def _coerce_alias(self, alias_or_result):
        if isinstance(alias_or_result, ThreadResult):
            return alias_or_result.alias
        if isinstance(alias_or_result, dict):
            return alias_or_result.get("alias")
        return alias_or_result

'''
        + methods
        + '''

    # --- Spec factories for tau.parallel() ---

'''
        + factories
        + '''


def exec_cell(code, namespace):
    """Execute a code cell in the given namespace.

    Returns (output, error, stdout, stderr).
    If the last statement is an expression, its repr is returned as output.
    """
    stdout_buf = io.StringIO()
    stderr_buf = io.StringIO()
    output = None
    error = None

    try:
        tree = ast.parse(code)
        last_expr = None
        # If the last statement is a bare expression, extract it
        # so we can eval it and return its value (REPL-style).
        if tree.body and isinstance(tree.body[-1], ast.Expr):
            last_expr = tree.body.pop()

        with contextlib.redirect_stdout(stdout_buf), contextlib.redirect_stderr(stderr_buf):
            if tree.body:
                compiled = compile(tree, "<cell>", "exec")
                exec(compiled, namespace)
            if last_expr:
                expr_code = compile(
                    ast.Expression(body=last_expr.value), "<cell>", "eval"
                )
                result = eval(expr_code, namespace)
                if result is not None:
                    output = repr(result)
    except Exception:
        error = traceback.format_exc()

    return output, error, stdout_buf.getvalue(), stderr_buf.getvalue()


def main():
    namespace = {
        "tau": TauProxy(),
'''
        + namespace_results
        + '''
        "__name__": "__main__",
    }

    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            msg = json.loads(line)
        except json.JSONDecodeError:
            continue

        msg_type = msg.get("type")

        if msg_type == "shutdown":
            break

        if msg_type == "exec":
            cell_id = msg["cell_id"]
            code = msg["code"]
            output, error, stdout, stderr = exec_cell(code, namespace)
            result = {
                "type": "result",
                "cell_id": cell_id,
                "output": output,
                "error": error,
                "stdout": stdout,
                "stderr": stderr,
            }
            sys.stdout.write(json.dumps(result) + "\\n")
            sys.stdout.flush()


if __name__ == "__main__":
    main()
'''
    )


def render_reference(manifest: dict[str, Any]) -> str:
    lines = [
        HEADER_MD.rstrip(),
        "## Tau Python API",
        "",
        "The `py_repl` namespace exposes a persistent `tau` object for programmatic orchestration.",
        "",
        "### Methods",
        "",
    ]
    for method in manifest["methods"]:
        lines.extend(
            [
                f"- `tau.{method['signature'].replace('self, ', '').replace('(self)', '()')}` -> `{method['return']}`",
                f"  {method['summary']}",
            ]
        )
    lines.extend(["", "### Parallel Specs", ""])
    for factory in manifest["factories"]:
        lines.append(f"- `tau.{factory['signature']}`: {factory['summary']}")
    lines.extend(["", "### Result Types", ""])
    for result in manifest["result_types"]:
        fields = ", ".join(field["name"] for field in result["fields"])
        lines.append(f"- `{result['name']}` fields: {fields}")
    lines.extend(["", "### Environment", ""])
    for env in manifest["environment"]:
        lines.append(f"- `tau.{env['name']}`: {env['description']}")
    lines.extend(["", "### Examples", ""])
    lines.append("```python")
    for method in manifest["methods"]:
        lines.append(method["example"])
    lines.append("```")
    return "\n".join(lines) + "\n"


def render_description(manifest: dict[str, Any]) -> str:
    return textwrap.fill(manifest["description"], width=100) + "\n"


def render_guideline(manifest: dict[str, Any]) -> str:
    return textwrap.fill(manifest["guideline"], width=100) + "\n"


def generated_outputs(manifest: dict[str, Any]) -> dict[pathlib.Path, str]:
    return {
        KERNEL_PATH: render_kernel(manifest),
        REFERENCE_PATH: render_reference(manifest),
        DESCRIPTION_PATH: render_description(manifest),
        GUIDELINE_PATH: render_guideline(manifest),
    }


def check_or_write(outputs: dict[pathlib.Path, str], check: bool) -> int:
    failures = 0
    for path, content in outputs.items():
        if check:
            existing = path.read_text() if path.exists() else ""
            if existing != content:
                failures += 1
                diff = difflib.unified_diff(
                    existing.splitlines(keepends=True),
                    content.splitlines(keepends=True),
                    fromfile=str(path),
                    tofile=f"{path} (generated)",
                )
                sys.stderr.writelines(diff)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    manifest = load_manifest()
    failures = check_or_write(generated_outputs(manifest), args.check)
    if failures:
        print(f"{failures} generated file(s) are stale; run scripts/generate-py-tau-api.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
